#!/usr/bin/env python3
"""Backtest historical swing setups generated by detect_historical_swing_setups.py.

This is an isolated swing-system replay. It stores results in
`historical_swing_backtest_runs` and `historical_swing_backtest_trades`, not in
production `backtest_runs`.
"""
from __future__ import annotations

import argparse
import json
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def db_path_from_env() -> Path:
    configured = os.getenv("TRADINGVIEW_MCP_DB_PATH") or os.getenv("TRAD_SIGNAL_DB_PATH")
    return Path(configured).expanduser() if configured else Path.home() / ".tradingview-mcp" / "trading_signals.sqlite3"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def ensure_schema(con: sqlite3.Connection) -> None:
    con.executescript(
        """
        CREATE TABLE IF NOT EXISTS historical_swing_backtest_runs (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          symbol TEXT NOT NULL,
          exchange TEXT NOT NULL,
          timeframe TEXT NOT NULL,
          params_json TEXT,
          setup_count INTEGER NOT NULL,
          total_trades INTEGER NOT NULL,
          wins INTEGER NOT NULL,
          losses INTEGER NOT NULL,
          time_exits INTEGER NOT NULL,
          win_rate REAL NOT NULL,
          expectancy_r REAL NOT NULL,
          avg_mfe REAL NOT NULL,
          avg_mae REAL NOT NULL,
          max_loss_streak INTEGER NOT NULL,
          summary_json TEXT,
          created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS historical_swing_backtest_trades (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          run_id INTEGER NOT NULL,
          setup_id INTEGER NOT NULL,
          direction TEXT NOT NULL,
          setup_type TEXT NOT NULL,
          session_label TEXT,
          entry_ts INTEGER NOT NULL,
          entry_time TEXT NOT NULL,
          entry_price REAL NOT NULL,
          sl REAL NOT NULL,
          tp REAL NOT NULL,
          exit_ts INTEGER,
          exit_time TEXT,
          exit_price REAL,
          result TEXT NOT NULL,
          r_multiple REAL NOT NULL,
          mfe REAL NOT NULL,
          mae REAL NOT NULL,
          hold_bars INTEGER NOT NULL,
          metadata_json TEXT,
          FOREIGN KEY(run_id) REFERENCES historical_swing_backtest_runs(id)
        );
        CREATE INDEX IF NOT EXISTS idx_historical_swing_backtest_trades_run
        ON historical_swing_backtest_trades(run_id, entry_ts);
        """
    )


def load_candles(con: sqlite3.Connection, symbol: str, exchange: str, timeframe: str) -> list[sqlite3.Row]:
    return con.execute(
        """
        SELECT * FROM historical_candles
        WHERE UPPER(symbol)=UPPER(?) AND UPPER(exchange)=UPPER(?) AND timeframe=?
        ORDER BY ts ASC
        """,
        (symbol, exchange, timeframe),
    ).fetchall()


def load_setups(con: sqlite3.Connection, symbol: str, exchange: str, timeframe: str, min_score: int, allowed_sessions: set[str] | None) -> list[sqlite3.Row]:
    rows = con.execute(
        """
        SELECT s.* FROM historical_swing_setups s
        WHERE UPPER(symbol)=UPPER(?) AND UPPER(exchange)=UPPER(?) AND timeframe=? AND score>=?
        ORDER BY ts ASC, id ASC
        """,
        (symbol, exchange, timeframe, min_score),
    ).fetchall()
    if allowed_sessions:
        return [r for r in rows if session_label(str(r["datetime_utc"])) in allowed_sessions]
    return rows


def session_label(datetime_utc: str) -> str:
    try:
        dt = datetime.fromisoformat(datetime_utc.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        hour_ict = (dt.astimezone(timezone.utc).hour + 7) % 24
    except Exception:
        return "unknown"
    if 6 <= hour_ict < 14:
        return "Asia"
    if 14 <= hour_ict < 19:
        return "London"
    if 19 <= hour_ict < 23:
        return "London/NY overlap"
    return "NY/late"


def simulate(setup: sqlite3.Row, candles: list[sqlite3.Row], ts_index: dict[int, int], max_hold_bars: int, entry_window_bars: int, partial_mfe: float | None = None) -> dict[str, Any] | None:
    start_i = ts_index.get(int(setup["ts"]))
    if start_i is None:
        return None
    direction = str(setup["direction"])
    entry_low, entry_high = float(setup["entry_low"]), float(setup["entry_high"])
    sl, tp = float(setup["sl"]), float(setup["tp1"])
    entry_c = None
    entry_i = -1
    for j in range(start_i + 1, min(len(candles), start_i + 1 + entry_window_bars)):
        c = candles[j]
        if float(c["low"]) <= entry_high and float(c["high"]) >= entry_low:
            entry_c = c
            entry_i = j
            break
    if entry_c is None:
        return None
    entry = min(max(float(entry_c["open"]), entry_low), entry_high)
    risk = max(0.01, abs(entry - sl))
    mfe = mae = 0.0
    result = "TIME_EXIT"
    exit_c = candles[min(len(candles) - 1, entry_i + max_hold_bars)]
    exit_price = float(exit_c["close"])
    hold = 0
    be_active = False
    partial_taken = False
    for j in range(entry_i, min(len(candles), entry_i + max_hold_bars)):
        c = candles[j]
        high, low = float(c["high"]), float(c["low"])
        hold = j - entry_i + 1
        if direction == "BUY":
            mfe = max(mfe, high - entry)
            mae = max(mae, entry - low)
            if partial_mfe is not None and not partial_taken and mfe >= partial_mfe:
                partial_taken = True
                be_active = True
            effective_sl = entry if be_active else sl
            hit_sl, hit_tp = low <= effective_sl, high >= tp
        else:
            mfe = max(mfe, entry - low)
            mae = max(mae, high - entry)
            if partial_mfe is not None and not partial_taken and mfe >= partial_mfe:
                partial_taken = True
                be_active = True
            effective_sl = entry if be_active else sl
            hit_sl, hit_tp = high >= effective_sl, low <= tp
        # Conservative same-candle ordering: SL before TP.
        if hit_sl and hit_tp:
            result, exit_price, exit_c = ("PARTIAL_BE" if partial_taken else "BE") if be_active else "SL", effective_sl, c
            break
        if hit_sl:
            result, exit_price, exit_c = ("PARTIAL_BE" if partial_taken else "BE") if be_active else "SL", effective_sl, c
            break
        if hit_tp:
            result, exit_price, exit_c = "TP", tp, c
            break
    if result == "TP":
        r_mult = abs(tp - entry) / risk
    elif result == "SL":
        r_mult = -1.0
    elif result == "PARTIAL_BE":
        r_mult = 0.25
    elif result == "BE":
        r_mult = 0.0
    else:
        r_mult = (exit_price - entry) / risk if direction == "BUY" else (entry - exit_price) / risk
    return {
        "setup_id": setup["id"], "direction": direction, "setup_type": setup["setup_type"],
        "session_label": session_label(str(entry_c["datetime_utc"])), "entry_ts": int(entry_c["ts"]), "entry_time": str(entry_c["datetime_utc"]),
        "entry_price": entry, "sl": sl, "tp": tp, "exit_ts": int(exit_c["ts"]), "exit_time": str(exit_c["datetime_utc"]),
        "exit_price": exit_price, "result": result, "r_multiple": r_mult, "mfe": mfe, "mae": mae, "hold_bars": hold,
        "metadata": {"score": setup["score"], "components": json.loads(setup["components_json"] or "{}"), "partial_mfe": partial_mfe},
    }


def max_loss_streak(trades: list[dict[str, Any]]) -> int:
    streak = worst = 0
    for t in trades:
        if t["result"] == "SL":
            streak += 1; worst = max(worst, streak)
        elif t["result"] in {"TP", "BE", "PARTIAL_BE"}:
            streak = 0
    return worst


def summarize(trades: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(trades)
    wins = sum(1 for t in trades if t["result"] in {"TP", "PARTIAL_BE"})
    losses = sum(1 for t in trades if t["result"] == "SL")
    time_exits = sum(1 for t in trades if t["result"] == "TIME_EXIT")
    return {
        "total_trades": total, "wins": wins, "losses": losses, "time_exits": time_exits,
        "win_rate": wins / total * 100 if total else 0.0,
        "expectancy_r": sum(float(t["r_multiple"]) for t in trades) / total if total else 0.0,
        "avg_mfe": sum(float(t["mfe"]) for t in trades) / total if total else 0.0,
        "avg_mae": sum(float(t["mae"]) for t in trades) / total if total else 0.0,
        "max_loss_streak": max_loss_streak(trades),
    }


def store_run(con: sqlite3.Connection, symbol: str, exchange: str, timeframe: str, params: dict[str, Any], setup_count: int, trades: list[dict[str, Any]]) -> int:
    s = summarize(trades)
    cur = con.execute(
        """
        INSERT INTO historical_swing_backtest_runs
        (symbol, exchange, timeframe, params_json, setup_count, total_trades, wins, losses, time_exits, win_rate, expectancy_r, avg_mfe, avg_mae, max_loss_streak, summary_json, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (symbol.upper(), exchange.upper(), timeframe, json.dumps(params, sort_keys=True), setup_count, s["total_trades"], s["wins"], s["losses"], s["time_exits"], s["win_rate"], s["expectancy_r"], s["avg_mfe"], s["avg_mae"], s["max_loss_streak"], json.dumps({"recent_trades": trades[-5:]}, ensure_ascii=False, sort_keys=True), utc_now()),
    )
    if cur.lastrowid is None:
        raise RuntimeError("SQLite did not return a swing backtest run id")
    run_id = int(cur.lastrowid)
    for t in trades:
        con.execute(
            """
            INSERT INTO historical_swing_backtest_trades
            (run_id, setup_id, direction, setup_type, session_label, entry_ts, entry_time, entry_price, sl, tp, exit_ts, exit_time, exit_price, result, r_multiple, mfe, mae, hold_bars, metadata_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (run_id, t["setup_id"], t["direction"], t["setup_type"], t["session_label"], t["entry_ts"], t["entry_time"], t["entry_price"], t["sl"], t["tp"], t["exit_ts"], t["exit_time"], t["exit_price"], t["result"], t["r_multiple"], t["mfe"], t["mae"], t["hold_bars"], json.dumps(t["metadata"], ensure_ascii=False, sort_keys=True)),
        )
    return run_id


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--symbol", default="XAUUSD")
    p.add_argument("--exchange", default="OANDA")
    p.add_argument("--timeframe", default="15m")
    p.add_argument("--db-path", default=str(db_path_from_env()))
    p.add_argument("--min-score", type=int, default=55)
    p.add_argument("--max-hold-bars", type=int, default=32)
    p.add_argument("--entry-window-bars", type=int, default=6)
    p.add_argument("--partial-mfe", type=float, default=None)
    p.add_argument("--allowed-sessions")
    p.add_argument("--no-store", action="store_true")
    p.add_argument("--json", action="store_true")
    args = p.parse_args(argv)
    allowed_sessions = {x.strip() for x in args.allowed_sessions.split(",") if x.strip()} if args.allowed_sessions else None
    params = {"min_score": args.min_score, "max_hold_bars": args.max_hold_bars, "entry_window_bars": args.entry_window_bars, "partial_mfe": args.partial_mfe, "allowed_sessions": sorted(allowed_sessions) if allowed_sessions else None}
    with sqlite3.connect(Path(args.db_path).expanduser()) as con:
        con.row_factory = sqlite3.Row
        ensure_schema(con)
        candles = load_candles(con, args.symbol, args.exchange, args.timeframe)
        setups = load_setups(con, args.symbol, args.exchange, args.timeframe, args.min_score, allowed_sessions)
        ts_index = {int(c["ts"]): i for i, c in enumerate(candles)}
        trades = [t for s in setups if (t := simulate(s, candles, ts_index, args.max_hold_bars, args.entry_window_bars, args.partial_mfe)) is not None]
        result = {"symbol": args.symbol.upper(), "exchange": args.exchange.upper(), "timeframe": args.timeframe, "setup_count": len(setups), "params": params, **summarize(trades)}
        if not args.no_store:
            result["run_id"] = store_run(con, args.symbol, args.exchange, args.timeframe, params, len(setups), trades)
            con.commit()
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(f"Swing backtest #{result.get('run_id','-')} setups={len(setups)} trades={result['total_trades']} WR={result['win_rate']:.1f}% ExpR={result['expectancy_r']:.2f} maxLS={result['max_loss_streak']}")
        print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
